<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2016 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

// Create shortcuts to some parameters.
$params  = $this->item->params;
$images  = json_decode($this->item->images);
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);
JHtml::_('behavior.caption');
// Load Template helper
$this->template = JFactory::getApplication()->getTemplate();
include_once JPATH_THEMES . '/' . $this->template . '/helper.php';
//// Load JLayouts helper
//require_once JPATH_THEMES . '/' . $this->template . '/html/layouts/perfectlayout/render.php';

$showfulltextimage = PWTTemplateHelper::getParam('show_fulltextimage');

?>
<div class="blog">
	<div class="card item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
		<meta itemprop="inLanguage"
		      content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>"/>
		<?php if ($this->params->get('show_page_heading')) : ?>
			<div class="page-header">
				<h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
			</div>
		<?php endif;
		if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative)
		{
			echo $this->item->pagination;
		}
		?>

		<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
		<?php if (!$params->get('show_intro')) : echo $this->item->event->afterDisplayTitle; endif; ?>
		<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
		<?php echo $this->item->event->beforeDisplayContent; ?>


		<?php if ($params->get('access-view')):

			switch (true)
			{
				// TODO: call for image_intro instead of image_fulltext. Lazyness of author. :-)
				case (isset($images->image_intro) && !empty($images->image_intro) && $this->item->catid == 37):
					echo '<div class="card__image card__image--border">';
					echo JLayoutHelper::render('joomla.content.intro_image', $this->item);
					echo '</div>';
					break;
				case (isset($images->image_intro) && !empty($images->image_intro)):
					echo '<div class="card__image">';
					echo JLayoutHelper::render('joomla.content.intro_image', $this->item);
					echo '</div>';
					break;
				default:
					echo '<div class="card__image">';
					echo '&nbsp;';
					echo '</div>';
			}

			?>


			<div class="card__content<?php echo $showfulltextimage ? "" : " card__content--hideimage"; ?>">
				<div class="card__header">
					<?php echo JLayoutHelper::render('perfectlayout.template.content.create_date', array('date' => $this->item->created, 'class' => 'blog', 'format' => 'DATE_FORMAT_LC4', 'show_create_date' => $params->get('show_publish_date', 1))); ?>

					<h1 itemprop="name">
						<?php echo $this->item->title; ?>
					</h1>

					<?php // Content is generated by content plugin event "onContentAfterTitle"
					?>
					<?php echo $this->item->event->afterDisplayTitle; ?>
				</div>

				<div class="card__body<?php echo($params->get('show_publish_date') ? ' card__body--create' : ''); ?>">

					<?php // Content is generated by content plugin event "onContentBeforeDisplay"
					?>
					<?php echo $this->item->event->beforeDisplayContent; ?>


					<?php echo $this->item->text; ?>
				</div>
			</div>


			<?php
			if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative):
				echo $this->item->pagination;
			endif;
			?>
			<?php if (isset ($this->item->toc)) :
			echo $this->item->toc;
		endif; ?>


			<?php if ($info == 1 || $info == 2) : ?>
			<?php if ($useDefList) : ?>
				<?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
			<?php endif; ?>
		<?php endif; ?>

			<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) : ?>
			<?php echo $this->loadTemplate('links'); ?>
		<?php endif; ?>

			<?php // Optional teaser intro text for guests
			?>
		<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
			<?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
			<?php echo JHtml::_('content.prepare', $this->item->introtext); ?>
			<?php // Optional link to let them register to see the whole article. ?>
			<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
				<?php $menu = JFactory::getApplication()->getMenu(); ?>
				<?php $active = $menu->getActive(); ?>
				<?php $itemId = $active->id; ?>
				<?php $link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
				<?php $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
				<p class="readmore">
					<a href="<?php echo $link; ?>" class="register">
						<?php $attribs = json_decode($this->item->attribs); ?>
						<?php
						if ($attribs->alternative_readmore == null) :
							echo JText::_('COM_CONTENT_REGISTER_TO_READ_MORE');
						elseif ($readmore = $attribs->alternative_readmore) :
							echo $readmore;
							if ($params->get('show_readmore_title', 0) != 0) :
								echo JHtml::_('string.truncate', ($this->item->title), $params->get('readmore_limit'));
							endif;
						elseif ($params->get('show_readmore_title', 0) == 0) :
							echo JText::sprintf('COM_CONTENT_READ_MORE_TITLE');
						else :
							echo JText::_('COM_CONTENT_READ_MORE');
							echo JHtml::_('string.truncate', ($this->item->title), $params->get('readmore_limit'));
						endif; ?>
					</a>
				</p>
			<?php endif; ?>
		<?php endif; ?>


		<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
		<?php echo $this->item->event->afterDisplayContent; ?>

	</div>
	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative):
		echo str_ireplace('rel="', 'class="btn--ghost--inverse" rel="', $this->item->pagination);
		?>
	<?php endif; ?>
</div>
